[package]
name = "s3_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.4"
aws-sdk-s3 = "1.40.0"
aws-sdk-sts = "1.34.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3.30"